### ISSUE TITLE
XCode Build Compile Non-Jailbroken Device

### ISSUE THREAD

**Issue by CollinCraig** [ilhanraja/StreakNotify#1]
I have been trying to compile this for a non-jailbroken device, and have gone ahead and attempted to fix some errors but this happens
[1;31m> [1;3;39mMaking all for tweak StreakNotify…[m
[0;33m==> [1;39mLinking tweak StreakNotify (armv7)…[m
ld: warning: directory not found for option '-L~/theos/lib'
ld: warning: directory not found for option '-L~/theos/vendor/lib'
ld: warning: directory not found for option '-F~/theos/vendor/lib'
ld: library not found for -lrocketbootstrap
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [/Users/collincraig/Downloads/StreakNotify/.theos/obj/debug/armv7/StreakNotify.dylib] Error 1
make[2]: *** [/Users/collincraig/Downloads/StreakNotify/.theos/obj/debug/armv7/StreakNotify.dylib] Error 2
make[1]: *** [internal-library-all_] Error 2
make: *** [StreakNotify.all.tweak.variables] Error 2
Command /usr/bin/make failed with exit code 2

**Comment by CollinCraig** [comment]
This happens when it runs the make

**Comment by YungRaj** [comment]
Your Theos build paths are wrong and you don't have RocketBootstrap placed in the lib folder so that it can be linked. You should recreate the build environment using the method provided on GitHub.

Also, if you're going to attempt making changes to my project, fork it and then submit a pull request once the changes have been made.

I haven't been around to fix the issues since DRM within Snapchat has been affecting StreakNotify and due to college I haven't had time to update.

I'll try to take a look at updating the tweak later during the Summer.

**Comment by CollinCraig** [comment]
Okay thanks, I have an iPhone 7 and unfortunately can't jailbreak due to my firmware being 10.3. But this is an amazing tweak I can't wait until it works on non-jailbroken devices.
